#!/usr/bin/env python

from util import *

def main(args):
    if len(args) != 1:
        usage('<repository>')
    else:
        repo = args[0]
        path = os.path.join('bundle', vim_humanish(repo))
        git('submodule', 'add', repo, path)

run(main)
